<template>
  <div>
    <b-form-textarea
      v-model="sequences"
      placeholder="enter sequence"
      rows="4"
      class="my-3"
    ></b-form-textarea>
    <b-button variant="outline-secondary" @click="transformSequences">
      submit
    </b-button>
  </div>
</template>
<script>
import { parse as fastaParse } from "biojs-io-fasta"

export default {
  data() {
    return {
      sequences:
        ">NC_001653.2 Hepatitis delta virus, complete genome\nATGAGCCAAGTTCCGAACAAGGATTCGCGGGGAGGATAGATCAGCGCCCGAGAGGGGTGAGTCGGTAAAG\nAGCATTGGAACGTCGGAGATACAACTCCCAAGAAGGAAAAAAGAGAAAGCAAGAAGCGGATGAATTTCCC\nCATAACGCCAGTGAAACTCTAGGAAGGGGAAAGAGGGAAGGTGGAAGAGAAGGAGGCGGGCCTCCCGATC\nCGAGGGGCCCGGCGGCCAAGTTTGGAGGACACTCCGGCCCGAAGGGTTGAGAGTACCCCAGAGGGAGGAA\nGCCACACGGAGTAGAACAGAGAAATCACCTCCAGAGGACCCCTTCAGCGAACAGAGAGCGCATCGCGAGA\nGGGAGTAGACCATAGCGATAGGAGGGGATGCTAGGAGTTGGGGGAGACCGAAGCGAGGAGGAAAGCAAAG\nAGAGCAGCGGGGCTAGCAGGTGGGTGTTCCGCCCCCCGAGAGGGGACGAGTGAGGCTTATCCCGGGGAAC\nTCGACTTATCGTCCCCACATAGCAGACTCCCGGACCCCCTTTCAAAGTGACCGAGGGGGGTGACTTTGAA\nCATTGGGGACCAGTGGAGCCATGGGATGCTCCTCCCGATTCCGCCCAAGCTCCTTCCCCCCAAGGGTCGC\nCCAGGAATGGCGGGACCCCACTCTGCAGGGTCCGCGTTCCATCCTTTCTTACCTGATGGCCGGCATGGTC\nCCAGCCTCCTCGCTGGCGCCGGCTGGGCAACATTCCGAGGGGACCGTCCCCTCGGTAATGGCGAATGGGA\nCCCACAAATCTCTCTAGCTTCCCAGAGAGAAGCGAGAGAAAAGTGGCTCTCCCTTAGCCATCCGAGTGGA\nCGTGCGTCCTCCTTCGGATGCCCAGGTCGGACCGCGAGGAGGTGGAGATGCCATGCCGACCCGAAGAGGA\nAAGAAGGACGCGAGACGCAAACCTGCGAGTGGAAACCCGCTTTATTCACTGGGGTCGACAACTCTGGGGA\nGAGGAGGGAGGGTCGGCTGGGAAGAGTATATCCTATGGGAATCCCTGGCTTCCCCTTATGTCCAGTCCCT\nCCCCGGTCCGAGTAAAGGGGGACTCCGGGACTCCTTGCATGCTGGGGACGAAGCCGCCCCCGGGCGCTCC\nCCTCGTTCCACCTTCGAGGGGGTTCACACCCCCAACCTGCGGGCCGGCTATTCTTCTTTCCCTTCTCTCG\nTCTTCCTCGGTCAACCTCCTAAGTTCCTCTTCCTCCTCCTTGCTGAGGTTCTTTCCCCCCGCCGATAGCT\nGCTTTCTCTTGTTCTCGAGGGCCTTCCTTCGTCGGTGATCCTGCCTCTCCTTGTCGGTGAATCCTCCCCT\nGGAAGGCCTCTTCCTAGGTCCGGAGTCTACTTCCATCTGGTCCGTTCGGGCCCTCTTCGCCGGGGGAGCC\nCCCTCTCCATCCTTATCTTTCTTTCCGAGAATTCCTTTGATGTTTCCCAGCCAGGGATGTTCATCCTCAA\nGTTTCTTGATTTTCTTCTTAACCTTCCGGAGGTCTCTCTCGAGTTCCTCTAACTTCTTTCTTCCGCTCAC\nCCACTGCTCGAGAACCTCTTCTCTCCCCCCGCGGTTTTTCCTTCCTTCGGGCCGGCTCATCTTCGACTAG\nAGGCGACGGTCCTCAGTACTCTTACTCTTTTCTGTAAAGAGGAGACTGCTGGCCCTGTCGCCCAAGTTCG\nAG",
    }
  },
  methods: {
    transformSequences() {
      for (const sequence of fastaParse(this.sequences)) {
        this.$store.dispatch("transformSequence", {
          description: sequence.name,
          sequence: sequence.seq,
          method: "yau_bp",
        })
      }
    },
  },
}
</script>
