<template>
  <b-jumbotron v-if="sequenceCount === 0" fluid bg-variant="light">
    <template #header>Turn DNA into graphs.</template>

    <template #lead>
      This is a simple hero unit, a simple jumbotron-style component for calling
      extra attention to featured content or information.
    </template>

    <hr class="my-4" />

    <p>
      It uses utility classes for typography and spacing to space content out
      within the larger container.
    </p>

    <b-button variant="outline-primary" href="#">Load Example</b-button>
    <b-button variant="outline-success" href="#">Upload File</b-button>
    <p class="mt-3">Or paste a FASTA-formatted sequence:</p>
    <b-form-textarea
      v-model="pastedSequences"
      placeholder="enter sequence"
      rows="4"
      class="my-3"
    ></b-form-textarea>
    <b-button variant="outline-secondary" @click="transformSequences">
      submit
    </b-button>
  </b-jumbotron>
</template>
<script>
import { parse as fastaParse } from "biojs-io-fasta"
import { mapState } from "vuex"

export default {
  data() {
    return {
      pastedSequences:
        ">NC_001653.2 Hepatitis delta virus, complete genome\nATGAGCCAAGTTCCGAACAAGGATTCGCGGGGAGGATAGATCAGCGCCCGAGAGGGGTGAGTCGGTAAAG\nAGCATTGGAACGTCGGAGATACAACTCCCAAGAAGGAAAAAAGAGAAAGCAAGAAGCGGATGAATTTCCC\nCATAACGCCAGTGAAACTCTAGGAAGGGGAAAGAGGGAAGGTGGAAGAGAAGGAGGCGGGCCTCCCGATC\nCGAGGGGCCCGGCGGCCAAGTTTGGAGGACACTCCGGCCCGAAGGGTTGAGAGTACCCCAGAGGGAGGAA\nGCCACACGGAGTAGAACAGAGAAATCACCTCCAGAGGACCCCTTCAGCGAACAGAGAGCGCATCGCGAGA\nGGGAGTAGACCATAGCGATAGGAGGGGATGCTAGGAGTTGGGGGAGACCGAAGCGAGGAGGAAAGCAAAG\nAGAGCAGCGGGGCTAGCAGGTGGGTGTTCCGCCCCCCGAGAGGGGACGAGTGAGGCTTATCCCGGGGAAC\nTCGACTTATCGTCCCCACATAGCAGACTCCCGGACCCCCTTTCAAAGTGACCGAGGGGGGTGACTTTGAA\nCATTGGGGACCAGTGGAGCCATGGGATGCTCCTCCCGATTCCGCCCAAGCTCCTTCCCCCCAAGGGTCGC\nCCAGGAATGGCGGGACCCCACTCTGCAGGGTCCGCGTTCCATCCTTTCTTACCTGATGGCCGGCATGGTC\nCCAGCCTCCTCGCTGGCGCCGGCTGGGCAACATTCCGAGGGGACCGTCCCCTCGGTAATGGCGAATGGGA\nCCCACAAATCTCTCTAGCTTCCCAGAGAGAAGCGAGAGAAAAGTGGCTCTCCCTTAGCCATCCGAGTGGA\nCGTGCGTCCTCCTTCGGATGCCCAGGTCGGACCGCGAGGAGGTGGAGATGCCATGCCGACCCGAAGAGGA\nAAGAAGGACGCGAGACGCAAACCTGCGAGTGGAAACCCGCTTTATTCACTGGGGTCGACAACTCTGGGGA\nGAGGAGGGAGGGTCGGCTGGGAAGAGTATATCCTATGGGAATCCCTGGCTTCCCCTTATGTCCAGTCCCT\nCCCCGGTCCGAGTAAAGGGGGACTCCGGGACTCCTTGCATGCTGGGGACGAAGCCGCCCCCGGGCGCTCC\nCCTCGTTCCACCTTCGAGGGGGTTCACACCCCCAACCTGCGGGCCGGCTATTCTTCTTTCCCTTCTCTCG\nTCTTCCTCGGTCAACCTCCTAAGTTCCTCTTCCTCCTCCTTGCTGAGGTTCTTTCCCCCCGCCGATAGCT\nGCTTTCTCTTGTTCTCGAGGGCCTTCCTTCGTCGGTGATCCTGCCTCTCCTTGTCGGTGAATCCTCCCCT\nGGAAGGCCTCTTCCTAGGTCCGGAGTCTACTTCCATCTGGTCCGTTCGGGCCCTCTTCGCCGGGGGAGCC\nCCCTCTCCATCCTTATCTTTCTTTCCGAGAATTCCTTTGATGTTTCCCAGCCAGGGATGTTCATCCTCAA\nGTTTCTTGATTTTCTTCTTAACCTTCCGGAGGTCTCTCTCGAGTTCCTCTAACTTCTTTCTTCCGCTCAC\nCCACTGCTCGAGAACCTCTTCTCTCCCCCCGCGGTTTTTCCTTCCTTCGGGCCGGCTCATCTTCGACTAG\nAGGCGACGGTCCTCAGTACTCTTACTCTTTTCTGTAAAGAGGAGACTGCTGGCCCTGTCGCCCAAGTTCG\nAG",
    }
  },
  computed: {
    sequenceCount() {
      return Object.keys(this.sequences).length
    },
    ...mapState(["sequences"]),
  },
  methods: {
    transformSequences() {
      for (const sequence of fastaParse(this.pastedSequences)) {
        this.$store.dispatch("transformSequence", {
          description: sequence.name,
          sequence: sequence.seq,
        })
      }
    },
  },
}
</script>
