sequenceDiagram
    participant C as Client
    participant L as AWS Lambda
    participant S as AWS S3
    note over C: User uploads FASTA
    loop Every sequence in uploaded FASTA files

            C-xL:Submit sequence async

            activate L
        opt Not already saved?
            L->>S: Transform and save parquet.sz
        end

            L->>C:  Downsampled JSON
            deactivate L
    end
    note right of S: Data deleted in 24h
    note over C: User zooms in
    loop Every uploaded sequence hash
        C-xL: Async sequence query
        activate L
        L->>S: S3 Select query
        activate S
        S->>L: Selected data as CSV
        deactivate S
        L->>C: Downsampled JSON
        deactivate L
    end
