ARTICLE_FILE        = paper.md
PANDOC_SCHOLAR_PATH = /Users/BenjaminLee/Downloads/pandoc-scholar-2.0.1
PANDOC_LATEX_OPTIONS += --csl=nucleic-acids-research.csl
include $(PANDOC_SCHOLAR_PATH)/Makefile
