name: "Automerge Dependabot PRs"
on:
    - "pull_request"
jobs:
    merge:
        name: "Merge"
        runs-on: "ubuntu-latest"
        if: >
            github.event_name == 'pull_request' &&
            github.event.pull_request.draft == false && (
            github.event.action == 'opened' ||
            github.event.action == 'reopened' ||
            github.event.action == 'synchronize'
            ) && (
            github.actor == 'dependabot[bot]'
            )
        steps:
            - name: "Merge pull request"
            uses: "actions/github-script@v2"
            with:
                github-token: "$"
                script: |
                    const pullRequest = context.payload.pull_request
                    const repository = context.repo

                    await github.pulls.merge({
                        merge_method: "merge",
                        owner: repository.owner,
                        pull_number: pullRequest.number,
                        repo: repository.repo,
                    })